In [1]:
2+3

5

In [2]:
3+4
1+2

3

In [3]:
3+5
4+5;

In [4]:
?println

search: println print sprint pointer printstyled



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


In [5]:
typeof(3), typeof(3.5), typeof(3/3.55), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [6]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0

(Inf, -Inf, NaN)

In [7]:
typeof(1.0/0.0), typeof(1.0/(-0.0)), typeof(0.0/0.0)

(Float64, Float64, Float64)

In [8]:
for T in [Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128]
    println("$(lpad(T,7)): [$(typemin(T)), $(typemax(T))]")
end

   Int8: [-128, 127]
  Int16: [-32768, 32767]
  Int32: [-2147483648, 2147483647]
  Int64: [-9223372036854775808, 9223372036854775807]
 Int128: [-170141183460469231731687303715884105728, 170141183460469231731687303715884105727]
  UInt8: [0, 255]
 UInt16: [0, 65535]
 UInt32: [0, 4294967295]
 UInt64: [0, 18446744073709551615]
UInt128: [0, 340282366920938463463374607431768211455]


In [9]:
Int(2.0), Char(2), typeof(Char(2))

(2, '\x02', Char)

In [10]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [11]:
?promote

search: promote promote_type promote_rule promote_shape permute! precompile



```
promote(xs...)
```

Convert all arguments to a common type, and return them all (as a tuple). If no arguments can be converted, an error is raised.

See also: [`promote_type`](@ref), [`promote_rule`](@ref).

# Examples

```jldoctest
julia> promote(Int8(1), Float16(4.5), Float32(4.1))
(1.0f0, 4.5f0, 4.1f0)

julia> promote_type(Int8, Float16, Float32)
Float32

julia> reduce(Base.promote_typejoin, (Int8, Float16, Float32))
Real

julia> promote(1, "x")
ERROR: promotion of types Int64 and String failed to change any arguments
[...]

julia> promote_type(Int, String)
Any
```


In [12]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [13]:
f(4)

16

In [14]:
g(x)=x^2

g (generic function with 1 method)

In [15]:
g(8)

64

In [16]:
a=[4 7 6]

1×3 Matrix{Int64}:
 4  7  6

In [17]:
b=[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [18]:
a[2], b[2]

(7, 2)

In [19]:
a=1; b=2; c=3; d=4
Am=[a b; c d]

2×2 Matrix{Int64}:
 1  2
 3  4

In [20]:
Am[1,1], Am[1,2], Am[2,1], Am[2,2]

(1, 2, 3, 4)

In [21]:
aa = [1 2]

1×2 Matrix{Int64}:
 1  2

In [22]:
AA = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [23]:
aa*AA

1×2 Matrix{Int64}:
 7  10

In [24]:
aa'

2×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2

In [25]:
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [26]:
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

In [27]:
?read

search: read read! rpad real break isready readdir Threads isreal lpad secd rem



```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString)
```

Read the entire contents of a file as a `Vector{UInt8}`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [28]:
content = read("example.txt")

52-element Vector{UInt8}:
 0xd0
 0x9f
 0xd0
 0xb5
 0xd1
 0x80
 0xd0
 0xb2
 0xd0
 0xb0
 0xd1
 0x8f
 0x20
    ⋮
 0x81
 0xd1
 0x82
 0xd1
 0x80
 0xd0
 0xbe
 0xd0
 0xba
 0xd0
 0xb0
 0x0a

In [29]:
content = read("example.txt", String)

"Первая строка\nВторая строка\n"

In [30]:
?readline

search: readline readlines readlink readdir eachline readbytes! replace @inline



```
readline(io::IO=stdin; keep::Bool=false)
readline(filename::AbstractString; keep::Bool=false)
```

Read a single line of text from the given I/O stream or file (defaults to `stdin`). When reading from a file, the text is assumed to be encoded in UTF-8. Lines in the input end with `'\n'` or `"\r\n"` or the end of an input stream. When `keep` is false (as it is by default), these trailing newline characters are removed from the line before it is returned. When `keep` is true, they are returned as part of the line.

Return a `String`.   See also [`copyline`](@ref) to instead write in-place to another stream (which can be a preallocated [`IOBuffer`](@ref)).

See also [`readuntil`](@ref) for reading until more general delimiters.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readline("my_file.txt")
"JuliaLang is a GitHub organization."

julia> readline("my_file.txt", keep=true)
"JuliaLang is a GitHub organization.\n"

julia> rm("my_file.txt")
```

```julia-repl
julia> print("Enter your name: ")
Enter your name:

julia> your_name = readline()
Logan
"Logan"
```


In [31]:
content = readline("example.txt")

"Первая строка"

In [32]:
?readlines

search: readlines readline readlink readbytes! readdir eachline leading_ones



```
readlines(io::IO=stdin; keep::Bool=false)
readlines(filename::AbstractString; keep::Bool=false)
```

Read all lines of an I/O stream or a file as a vector of strings. Behavior is equivalent to saving the result of reading [`readline`](@ref) repeatedly with the same arguments and saving the resulting lines as a vector of strings.  See also [`eachline`](@ref) to iterate over the lines without reading them all at once.

# Examples

```jldoctest
julia> write("my_file.txt", "JuliaLang is a GitHub organization.\nIt has many members.\n");

julia> readlines("my_file.txt")
2-element Vector{String}:
 "JuliaLang is a GitHub organization."
 "It has many members."

julia> readlines("my_file.txt", keep=true)
2-element Vector{String}:
 "JuliaLang is a GitHub organization.\n"
 "It has many members.\n"

julia> rm("my_file.txt")
```


In [33]:
content = readlines("example.txt")

2-element Vector{String}:
 "Первая строка"
 "Вторая строка"

In [36]:
using DelimitedFiles

In [37]:
?readdlm

search: readdlm readdir read real read! readchomp isreadonly readlink isreadable



```
readdlm(source, T::Type; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt", Int64)
4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

julia> readdlm("delim_file.txt", Float64)
4×2 Matrix{Float64}:
 1.0  5.0
 2.0  6.0
 3.0  7.0
 4.0  8.0

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, T::Type; options...)
```

The end of line delimiter is taken as `\n`.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',', Float64)
4×2 Matrix{Float64}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> rm("delim_file.txt")
```

---

```
readdlm(source; options...)
```

The columns are assumed to be separated by one or more whitespaces. The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end;

julia> readdlm("delim_file.txt")
4×2 Matrix{Any}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar; options...)
```

The end of line delimiter is taken as `\n`. If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [1.1; 2.2; 3.3; 4.4];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Matrix{Float64}:
 1.0  1.1
 2.0  2.2
 3.0  3.3
 4.0  4.4

julia> z = ["a"; "b"; "c"; "d"];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x z], ',')
       end;

julia> readdlm("delim_file.txt", ',')
4×2 Matrix{Any}:
 1  "a"
 2  "b"
 3  "c"
 4  "d"

julia> rm("delim_file.txt")
```

---

```
readdlm(source, delim::AbstractChar, eol::AbstractChar; options...)
```

If all data is numeric, the result will be a numeric array. If some elements cannot be parsed as numbers, a heterogeneous array of numbers and strings is returned.

---

```
readdlm(source, delim::AbstractChar, T::Type, eol::AbstractChar; header=false, skipstart=0, skipblanks=true, use_mmap, quotes=true, dims, comments=false, comment_char='#')
```

Read a matrix from the source where each line (separated by `eol`) gives one row, with elements separated by the given delimiter. The source can be a text file, stream or byte array. Memory mapped files can be used by passing the byte array representation of the mapped segment as source.

If `T` is a numeric type, the result is an array of that type, with any non-numeric elements as `NaN` for floating-point types, or zero. Other useful values of `T` include `String`, `AbstractString`, and `Any`.

If `header` is `true`, the first row of data will be read as header and the tuple `(data_cells, header_cells)` is returned instead of only `data_cells`.

Specifying `skipstart` will ignore the corresponding number of initial lines from the input.

If `skipblanks` is `true`, blank lines in the input will be ignored.

If `use_mmap` is `true`, the file specified by `source` is memory mapped for potential speedups if the file is large. Default is `false`. On a Windows filesystem, `use_mmap` should not be set to `true` unless the file is only read once and is also not written to. Some edge cases exist where an OS is Unix-like but the filesystem is Windows-like.

If `quotes` is `true`, columns enclosed within double-quote (") characters are allowed to contain new lines and column delimiters. Double-quote characters within a quoted field must be escaped with another double-quote.  Specifying `dims` as a tuple of the expected rows and columns (including header, if any) may speed up reading of large files.  If `comments` is `true`, lines beginning with `comment_char` and text following `comment_char` in any line are ignored.

# Examples

```jldoctest
julia> using DelimitedFiles

julia> x = [1; 2; 3; 4];

julia> y = [5; 6; 7; 8];

julia> open("delim_file.txt", "w") do io
           writedlm(io, [x y])
       end

julia> readdlm("delim_file.txt", '\t', Int, '\n')
4×2 Matrix{Int64}:
 1  5
 2  6
 3  7
 4  8

julia> rm("delim_file.txt")
```


In [41]:
x = [2; 3; 2; 3];
y = ["a"; "b"; "a"; "b"];

open("test.txt", "w") do io
    for i in 1:length(x)
        println(io, string(x[i], " ", y[i]))
    end
end

In [42]:
readdlm("test.txt")

4×2 Matrix{Any}:
 2  "a"
 3  "b"
 2  "a"
 3  "b"

In [43]:
print("Hello, ")
print("world!")

Hello, world!

In [46]:
println("Hello, ")
print("world!")

Hello, 
world!

In [47]:
?show

search: show @show chown throw Cshort chop showable ispow2



```
show([io::IO = stdout], x)
```

Write a text representation of a value `x` to the output stream `io`. New types `T` should overload `show(io::IO, x::T)`. The representation used by `show` generally includes Julia-specific formatting and type information, and should be parseable Julia code when possible.

[`repr`](@ref) returns the output of `show` as a string.

For a more verbose human-readable text output for objects of type `T`, define `show(io::IO, ::MIME"text/plain", ::T)` in addition. Checking the `:compact` [`IOContext`](@ref) key (often checked as `get(io, :compact, false)::Bool`) of `io` in such methods is recommended, since some containers show their elements by calling this method with `:compact => true`.

See also [`print`](@ref), which writes un-decorated representations.

# Examples

```jldoctest
julia> show("Hello World!")
"Hello World!"
julia> print("Hello World!")
Hello World!
```

---

```
show(io::IO, mime, x)
```

The [`display`](@ref) functions ultimately call `show` in order to write an object `x` as a given `mime` type to a given I/O stream `io` (usually a memory buffer), if possible. In order to provide a rich multimedia representation of a user-defined type `T`, it is only necessary to define a new `show` method for `T`, via: `show(io, ::MIME"mime", x::T) = ...`, where `mime` is a MIME-type string and the function body calls [`write`](@ref) (or similar) to write that representation of `x` to `io`. (Note that the `MIME""` notation only supports literal strings; to construct `MIME` types in a more flexible manner use `MIME{Symbol("")}`.)

For example, if you define a `MyImage` type and know how to write it to a PNG file, you could define a function `show(io, ::MIME"image/png", x::MyImage) = ...` to allow your images to be displayed on any PNG-capable `AbstractDisplay` (such as IJulia). As usual, be sure to `import Base.show` in order to add new methods to the built-in Julia function `show`.

Technically, the `MIME"mime"` macro defines a singleton type for the given `mime` string, which allows us to exploit Julia's dispatch mechanisms in determining how to display objects of any given type.

The default MIME type is `MIME"text/plain"`. There is a fallback definition for `text/plain` output that calls `show` with 2 arguments, so it is not always necessary to add a method for that case. If a type benefits from custom human-readable output though, `show(::IO, ::MIME"text/plain", ::T)` should be defined. For example, the `Day` type uses `1 day` as the output for the `text/plain` MIME type, and `Day(1)` as the output of 2-argument `show`.

# Examples

```jldoctest
julia> struct Day
           n::Int
       end

julia> Base.show(io::IO, ::MIME"text/plain", d::Day) = print(io, d.n, " day")

julia> Day(1)
1 day
```

Container types generally implement 3-argument `show` by calling `show(io, MIME"text/plain"(), x)` for elements `x`, with `:compact => true` set in an [`IOContext`](@ref) passed as the first argument.


In [48]:
show([1, 2, 3])

[1, 2, 3]

In [49]:
show([1 2 3 ])

[1 2 3]

In [50]:
?write

search: write writedlm wait while stride iswritable closewrite



```
write(io::IO, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream. See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

The endianness of the written value depends on the endianness of the host system. Convert to/from a fixed endianness when writing/reading (e.g. using  [`htol`](@ref) and [`ltoh`](@ref)) to get results that are consistent across platforms.

You can write multiple values with the same `write` call. i.e. the following are equivalent:

```
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

Consistent serialization:

```jldoctest
julia> fname = tempname(); # random temporary filename

julia> open(fname,"w") do f
           # Make sure we write 64bit integer in little-endian byte order
           write(f,htol(Int64(42)))
       end
8

julia> open(fname,"r") do f
           # Convert back to host byte order and host integer type
           Int(ltoh(read(f,Int64)))
       end
42
```

Merging write calls:

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```

User-defined plain-data types without `write` methods can be written when wrapped in a `Ref`:

```jldoctest
julia> struct MyStruct; x::Float64; end

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, Ref(MyStruct(42.0)))
8

julia> seekstart(io); read!(io, Ref(MyStruct(NaN)))
Base.RefValue{MyStruct}(MyStruct(42.0))
```

---

```
write(filename::AbstractString, content)
```

Write the canonical binary representation of `content` to a file, which will be created if it does not exist yet or overwritten if it does exist.

Return the number of bytes written into the file.


In [51]:
io = IOBuffer()
write(io, "Hello, ", "world!")

13

In [52]:
open("output.txt", "w") do f
    write(f, "Это строка без перевода строки")
end

56

In [53]:
?parse

search: parse tryparse Base pairs falses parent



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.

---

```
parse(::Type{SimpleColor}, rgb::String)
```

An analogue of `tryparse(SimpleColor, rgb::String)` (which see), that raises an error instead of returning `nothing`.


In [59]:
a = "786"
# typeof(a)
b = parse(Int, a)
typeof(b)

Int64

In [61]:
parse(Float64, "3.1415")

3.1415

In [64]:
parse(Bool, "true")

true

In [65]:
parse(Int, "abc")

LoadError: ArgumentError: invalid base 10 digit 'a' in "abc"

In [66]:
parse(Int, "1011"; base=2)

11

In [67]:
parse(Int, "1F"; base=16)

31

In [68]:
a = 10 # Int
b = 3.5 # Float64
c = 2 + 3im # Complex
d = true # Bool
e = "Hello" # String

"Hello"

In [69]:
#сложение

sum_int = a + 5

15

In [70]:
a+b

13.5

In [71]:
b+c

5.5 + 3.0im

In [72]:
a+e

LoadError: MethodError: no method matching +(::Int64, ::String)
The function `+` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:596
  +(::Real, ::Complex{Bool})
   @ Base complex.jl:322
  +(::Integer, ::AbstractChar)
   @ Base char.jl:247
  ...


In [73]:
e+e

LoadError: MethodError: no method matching +(::String, ::String)
The function `+` exists, but no method is defined for this combination of argument types.
String concatenation is performed with * (See also: https://docs.julialang.org/en/v1/manual/strings/#man-concatenation).

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:596
  +(::Bool, ::Complex{Bool})
   @ Base complex.jl:308
  +(::Bool, ::Bool)
   @ Base bool.jl:166
  ...


In [74]:
d+d

2

In [75]:
true + false

1

In [76]:
false+false

0

In [77]:
c+d

3 + 3im

In [78]:
# вычитание

a - 4

6

In [79]:
b - a

-6.5

In [80]:
c - d

1 + 3im

In [81]:
c - b

-1.5 + 3.0im

In [82]:
# умножение

a*a

100

In [83]:
a*b

35.0

In [84]:
b*b

12.25

In [85]:
b*c

7.0 + 10.5im

In [86]:
c*c

-5 + 12im

In [87]:
c*d

2 + 3im

In [88]:
c*false

0 + 0im

In [89]:
2*e

LoadError: MethodError: no method matching *(::Int64, ::String)
The function `*` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:596
  *(::Real, ::Complex{Bool})
   @ Base complex.jl:330
  *(::Missing, ::Union{AbstractChar, AbstractString})
   @ Base missing.jl:174
  ...


In [90]:
# деление

a/4

2.5

In [91]:
b/a

0.35

In [92]:
c/b

0.5714285714285714 + 0.8571428571428571im

In [93]:
c/d

2.0 + 3.0im

In [94]:
true / false

Inf

In [96]:
# целочисленное деление

div(10, 4)

2

In [101]:
# остаток от деления

mod(10, 5)

0

In [102]:
# возведение в степень

a^2

100

In [103]:
b^a

275854.7353515625

In [104]:
c^a

-341525 - 145668im

In [105]:
c^d

2 + 3im

In [106]:
d^0

true

In [107]:
# извлечение корня

sqrt(a)

3.1622776601683795

In [108]:
sqrt(100)

10.0

In [109]:
sqrt(b)

1.8708286933869707

In [110]:
sqrt(c)

1.6741492280355401 + 0.8959774761298381im

In [111]:
sqrt(d)

1.0

In [114]:
# равенство

a == 10

true

In [115]:
# не равно

a != 10

false

In [118]:
a > b, a, b

(true, 10, 3.5)

In [119]:
a < b

false

In [121]:
a >= b

true

In [128]:
a <= d

false

In [129]:
true && true

true

In [130]:
true && false

false

In [131]:
true || false

true

In [132]:
true || true

true

In [133]:
!true

false

In [134]:
!false

true

In [142]:
# матрицы и векторы

a = [1 2 3]
c = [1 1 1]

1×3 Matrix{Int64}:
 1  1  1

In [143]:
b = [4, 5, 6]
d = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [139]:
m1 = [1 1 1; 2 2 2; 1 1 1]

3×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1

In [140]:
m2 = [2 2 2; 1 1 1; 2 2 2]

3×3 Matrix{Int64}:
 2  2  2
 1  1  1
 2  2  2

In [144]:
# сложение векторов и матриц

sum1 = a+c

1×3 Matrix{Int64}:
 2  3  4

In [145]:
sum2 = b+d

3-element Vector{Int64}:
 5
 7
 9

In [147]:
sum3 = m1 + m2

3×3 Matrix{Int64}:
 3  3  3
 3  3  3
 3  3  3

In [155]:
# вычитание векторов и матриц

diff1 = a-c

1×3 Matrix{Int64}:
 0  1  2

In [151]:
diff2 = b-d

3-element Vector{Int64}:
 3
 3
 3

In [153]:
diff3 = m1-m2

3×3 Matrix{Int64}:
 -1  -1  -1
  1   1   1
 -1  -1  -1

In [154]:
diff4 = m2-m1

3×3 Matrix{Int64}:
  1   1   1
 -1  -1  -1
  1   1   1

In [158]:
# скалярное произведение

using LinearAlgebra

dot_prod = dot(a, c)

6

In [159]:
dot(a, b)

32

In [160]:
dot(b, d)

32

In [161]:
dot(m1, m2)

18

In [163]:
transpose(a)

3×1 transpose(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [164]:
a'

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [165]:
m1'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  2  1
 1  2  1
 1  2  1

In [166]:
transpose(m1)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  2  1
 1  2  1
 1  2  1

In [167]:
b'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 4  5  6

In [168]:
scalar = 2

scalar * m1

3×3 Matrix{Int64}:
 2  2  2
 4  4  4
 2  2  2

In [169]:
scalar * a

1×3 Matrix{Int64}:
 2  4  6

In [170]:
scalar * b

3-element Vector{Int64}:
  8
 10
 12

In [171]:
a*b

1-element Vector{Int64}:
 32

In [173]:
a*m1

1×3 Matrix{Int64}:
 8  8  8

In [176]:
m1*b

3-element Vector{Int64}:
 15
 30
 15

In [177]:
m1*m2

3×3 Matrix{Int64}:
  5   5   5
 10  10  10
  5   5   5